"""App configuration parameters."""
ADDRESS_ROOT = "https://api.chess.com/pub/player"
DATA_FOLDER = "./data/"
MINIMAL_MONTH = "2022-07"
START_MONTH = "2023-01"
END_MONTH = "2023-05"
N_POSITIONS = 10
N_PROCS = 4
MAX_DEPTH = 14
N_GAMES_THRESHOLD = 3
